server:
  port: 8982
  
spring:
  application:
    name: service-registry
    
eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    server: 
      waitTimeInMsWhenSyncEmpty: 0